#ifndef DLT698PROCTOL_GLOBAL_H
#define DLT698PROCTOL_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(DLT698PROCTOL_LIBRARY)
#  define DLT698PROCTOLSHARED_EXPORT Q_DECL_EXPORT
#else
#  define DLT698PROCTOLSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // DLT698PROCTOL_GLOBAL_H
