#ifndef DLT698SERVICE_GLOBAL_H
#define DLT698SERVICE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(DLT698SERVICE_LIBRARY)
#  define DLT698SERVICESHARED_EXPORT Q_DECL_EXPORT
#else
#  define DLT698SERVICESHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // DLT698SERVICE_GLOBAL_H
